### ISSUE TITLE
Replace the Logout Button with a User Menu

### ISSUE THREAD

**Issue by mdeslippe** [mdeslippe/easy-tracker#142]
- The menu should be a button that contains the user's profile picture.
- When the button is clicked on, it should open a pop-up menu - this menu should have a button to logout.

**Comment by mdeslippe** [comment]
Going to put this off until later, I don't want to rush this and want to make sure this is fully accessible.

An example of how to implement it (not fully accessible, needs to be fixed):
```tsx
/**
 * Properties for the {@link DropDownMenu} component.
 */
export interface DropDownMenuProps extends ComponentProps<'div'> {
	/**
	 * A descriptive label that will be used for accessibility purposes.
	 */
	accessibilityLabel: string;

	/**
	 * The alignment of the expanded content, relative to the bottom of the button.
	 */
	align: 'left' | 'center' | 'right';

	/**
	 * The content that will be rendered inside of the drop down menu's button.
	 */
	buttonContent: ReactNode;

	/**
	 * The content that will be rendered when the drop down menu is expanded.
	 */
	children: ReactNode;
}

/**
 * A drop down menu component.
 *
 * @param props The component's properties.
 * @returns The drop down menu.
 */
export function DropDownMenu({
	accessibilityLabel,
	align,
	buttonContent,
	children,
	className,
	...props
}: DropDownMenuProps): JSX.Element {
	const [isOpen, setIsOpen] = useState<boolean>(false);

	useEffect(() => {
		const escapeHandler = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				event.stopPropagation();
				event.preventDefault();
				setIsOpen(false);
			}
		};

		window.addEventListener('keydown', escapeHandler, false);
		return () => window.removeEventListener('keydown', escapeHandler, false);
	}, []);

	return (
		<Fragment>
			{isOpen && (
				<div
					className='full-page-drop-down-overlay'
					role='button'
					aria-label='Close user menu'
					onClick={() => setIsOpen(false)}
				/>
			)}
			<div
				{...props}
				className={className ? `${className} drop-down-menu` : 'drop-down-menu'}
			>
				<button
					className='drop-down-button'
					aria-haspopup='menu'
					aria-expanded={isOpen}
					aria-label={accessibilityLabel}
					onClick={() => setIsOpen((status) => !status)}
				>
					{buttonContent}
				</button>
				{isOpen && <div className={`drop-down-content align-${align}`}>{children}</div>}
			</div>
		</Fragment>
	);
}
```
```css
/* Class Styling */
.full-page-drop-down-overlay {
	height: 100vh;
	left: 0;
	position: fixed;
	top: 0;
	width: 100vw;
}

.drop-down-menu {
	align-items: center;
	display: flex;
	height: 100%;
	justify-content: center;
	position: relative;
}

.drop-down-button {
	align-items: center;
	background: none;
	border: none;
	display: flex;
	justify-content: center;
	padding: 0px;
}

.drop-down-button:hover {
	cursor: pointer;
}

.drop-down-content {
	background: var(--secondary-color);
	border-radius: var(--normal-border-radius);
	box-shadow: 0 2px 5px 0 var(--tertiary-accent);
	opacity: 0;
	position: absolute;
	top: calc(100% + 0.25rem);
	transform: translateY(-10px);
}

.drop-down-content.align-left {
	animation: show 100ms 100ms cubic-bezier(0.38, 0.97, 0.56, 0.76) forwards;
	left: 0;
}

.drop-down-content.align-center {
	animation: show-center 100ms 100ms cubic-bezier(0.38, 0.97, 0.56, 0.76) forwards;
	left: 50%;
	transform: translateX(-50%);
}

.drop-down-content.align-right {
	animation: show 100ms 100ms cubic-bezier(0.38, 0.97, 0.56, 0.76) forwards;
	right: 0;
}

/* Animations */
@keyframes show {
	100% {
		opacity: 1;
		transform: translateY(0px);
	}
}

@keyframes show-center {
	100% {
		opacity: 1;
		transform: translateX(-50%) translateY(0px);
	}
}

```
